name: container

on:
  push:
    branches:
      - 'main'

using-an-action
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: image/
          push: true
          tags: ghcr.io/lruppert/ninjacape-mqtt-bridge:latest
          platforms: linux/arm/v6

